# This is a basic workflow to help you get started with Actions

name: Overleaf to GitHub CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "pdf/rounakvyas.pdf"

      - name: Remove if pdf exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
            rm pdf/rounakvyas.pdf
            echo "Removed previous resume......."
      
      - name: Run laton command to convert to pdf
        run: ./laton cv_7.tex > /dev/null 2>&1
      
      - name: wait for pdf to be created 
        run: sleep 5
        
      - name: Move pdf to folder
        run: mv cv_7.pdf pdf/rounakvyas.pdf
        
      - name: Push resume pdf to website
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACTIONS_RESUME_TOKEN }}
        with:
          source_file: 'pdf/rounakvyas.pdf'
          destination_repo: 'itsron717/rounakvyas.me'
          destination_folder: 'static'
          user_email: 'itsron143@gmail.com'
          user_name: 'itsron717'


